
<?php

use Quadro\Response\EnumLinkRelations;

$app = Quadro\Application::getInstance();
$app
    ->getResponse()
    ->addLink(EnumLinkRelations::Help , $app->getUrlRoot() . '/application', 'GET')
    ->addLink(EnumLinkRelations::Help , $app->getUrlRoot() . '/phpinfo', 'GET')
    ->addLink(EnumLinkRelations::Help , $app->getUrlRoot() . '/signup', 'GET')
    ->addLink(EnumLinkRelations::Help , $app->getUrlRoot() . '/signin', 'GET')
    ->setContent('This message is generated by the default Quadro API Framework URI handler.')
;
