<?php

use Quadro\Http\Response\EnumLinkRelations;

$app = Quadro\Application::getInstance();
$app
    ->getResponse()
    ->addMessage('This message is generated by the default Quadro API Framework URI handler.')
    ->addMessage('See linksTo section for more build in URI\'s')
    ->addLink(EnumLinkRelations::Help , $app->getUrlRoot() . '/application', 'GET')
    ->addLink(EnumLinkRelations::Help , $app->getUrlRoot() . '/phpinfo', 'GET')
    ->addLink(EnumLinkRelations::Help , $app->getUrlRoot() . '/signup', 'GET')
    ->addLink(EnumLinkRelations::Help , $app->getUrlRoot() . '/signin', 'GET')
;


